src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
Masari has a mandated ring size of 12 therefore this piece of code leftover from Monero is no longer needed
=> Remove wallet option to adjust the ring size

src/simplewallet/simplewallet.cpp
This fixes a bug where the lowest priority would be used if a priority string ("defualt", "low", etc) is not passed as an arg in `transfer`. If a priority is not set in the `transfer` command, then we can use the priority specified in `set priority`.
=> use default priority if one is not specified

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
When the CLI wallet is first startup without a proper daemon connection it will try to connect to the daemon, show an error upon failing, then continue  to try to refresh which will again fail and show the same error again. This PR silences the second error since one has already been shown just before the second.
=> CLI: only show daemon connection error once on wallet startup

src/simplewallet/simplewallet.cpp
Exit immediatly if wallet file does not exist when `--wallet-file` flag is used
=> CLI: exit if specified wallet file does not exist

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
One part was missing a `tr()`. This also switches to formatted strings as concentration wouldn't make sense in languages with different grammar structures.
=> CLI: Fix string handling for donation message

src/common/dns_utils.cpp
This is a subjectivly advanced feature and often confuses new users. Bump up the minimum log level to display this warning to log level 2 to avoid confusion but still easily accessible for debugging
=> dns_utils: bump up min log level for dns checkpoint warnings

src/cryptonote_basic/cryptonote_format_utils.cpp
When we fork to v6 cn_variant would be 6 - 4 = 2  even though we want to use variant 1.
cn_slow_hash technically only checks `if(variant > 0)` and then uses variant 1, but it is better to explicitly set cn_variant to 1 for v5 and v6, especially if we want to use a new variant (which would be variant 2) in the future.
=> cryptonote_format_utils: explicitly use cn variant 1 for version 6

src/wallet/wallet2.cpp, src/wallet/wallet2.h
only check nettypes when `refresh` is first invoked, not when pulling addition blocks.
=> wallet2: avoid unnecessary get_info calls

src/daemon/command_parser_executor.cpp
Don't just check for "true" or "false" strings, allow 0/1, true/false, yes/no, y/n
=> command_parser_executor: handle user input for optional miner params better

src/cryptonote_basic/miner.cpp, src/cryptonote_basic/miner.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/cryptonote_tx_utils.cpp, src/cryptonote_core/cryptonote_tx_utils.h, src/daemon/command_parser_executor.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/daemon_handler.cpp, tests/core_tests/block_reward.cpp, tests/core_tests/chaingen.cpp, tests/core_tests/transaction_tests.cpp, tests/performance_tests/multi_tx_test_base.h, tests/performance_tests/single_tx_test_base.h, tests/unit_tests/test_tx_utils.cpp
Use the subaddress public spend key as the generator point when creating the coinbase transaction public key if a subaddress is supplied for the miner reward.
=> allow mining to subaddresses

src/simplewallet/simplewallet.cpp
should use the proper unit set by the user in the wallet (masari, millisari, etc)
=> simplewallet: use correct unit for donation message

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/api/wallet2_api.h
The GUI wallet currently doesn't support multisig wallets and most wallets in general don't support multisig so they should be able to tell if a wallet opened is a multisig wallet.
=> wallet api: add isMultisig function

src/cryptonote_basic/cryptonote_basic.h, src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_basic/cryptonote_format_utils.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_tx_utils.cpp
Not suitable for mainnet. Restructures blocks to allow uncles blocks, include uncle blocks in block template when appropriate, miners automatically switch to the chain with the lowest top block hash, basic validation tests on uncles before getting added to the blockchain
=> uncle-mining: Initial uncle mining structure

src/crypto/crypto-ops.c, src/ringct/bulletproofs.cc, src/ringct/rctOps.cpp, src/ringct/rctOps.h
Check that input scalars are less than `l`, fix signum, reject points that aren't in the main subgroup.
Thanks to moneromooo and Kudelski Labs
=> RingCT: bulletproofs tweaks

src/wallet/wallet2.cpp
Otherwise the hash gets mushed up with the message and that's just awkward
=> wallet2: fix warning message formating

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h
adds get_blocks_json rpc endpoint. Grabs several blocks by height all at once and return the result as a JSON encoded string
Example usage:
`curl -X POST http://127.0.0.1:48081/get_blocks_json -d '{"heights":[20,5, 6218]}}' -H 'Content-Type: application/json'`
=> core rpc: get several blocks at once as json

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h
Allows you to get all transactions from a specific block height
Example usage:
`curl -X POST http://127.0.0.1:48081/gettransactions_by_height -d '{"heights":[6218,6159]}' -H 'Content-Type: application/json'`
=> core rpc: add get_transactions_by_height rpc call

src/rpc/core_rpc_server.cpp
This is no longer needed and simply bloats the response with 2x info
=> core rpc: remove legacy response from get_transactions

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
Adds an optional json_only parameter for the get_transaction_pool rpc endpoint which will leave the tx_blob data empty
=> core rpc: allow omission of binary data in get_transaction_pool

src/simplewallet/simplewallet.cpp
Since #106 wallet name and wallet file are no longer the same, so simplewallet text should be updated to reflect that change
=> simplewallet: make distinction between wallet file and wallet name

src/rpc/core_rpc_server.cpp
If you request the current block height you end up with an error message like "Too big height: 1692829, current blockchain height = 1692829", which doesn't make sense. Instead it should use the top block height (current block height - 1).
=> rpc: use current block height - 1 for top block height in err msgs

src/rpc/core_rpc_server.cpp
If a block is an uncle block than it is not an orphan, even if it is present in a "orphaned chain"
=> rpc: set orphan_status to false if uncle_status is true

src/cryptonote_core/cryptonote_core.cpp
Masari doesn't have a defined fork schedule
=> core: remove date based fork warning

src/rpc/core_rpc_server.cpp
If get_generated_coins is called in the middle of an initial/catch-up sync then the data will be based off the latest block in the database, not the actual top block by consensus, therefore returning an incorrect number. To stop this, check the sync status and return BUSY if needed.
=> rpc: check core status before fetching supply from top block

src/wallet/wallet2.cpp
Currently the only message is logged to the log file, leaving the wallet program to exit without telling why
=> wallet2: std out before exiting due to out consistency failure

src/wallet/api/wallet.cpp
Encountered an outright error when building the wallet GUI on OSX, which adding this solved. Strangely, this only reveals a problem when compiling the GUI. 
https://github.com/electronero/electronero/pull/45/files
many other projects have done this, it's a little obscure and lesser known problem.
=> Allows gui wallet to build via boost 1.67, (add a cast to satisfy Boost 1.67)

external/rapidjson/document.h, src/crypto/chacha.h, src/cryptonote_basic/account.cpp, src/daemon/rpc_command_executor.cpp
Fix compile failures under GCC 8.1. Follows similar PRs from monero: monero-project/monero#3851 and rapidjson: https://github.com/Tencent/rapidjson/pull/1323/files
=> gcc8 fixes

src/cryptonote_basic/miner.cpp
Masari fails to build against the latest version of boost (1.69) on Arch Linux.
=> boost-1.69 build fix

src/simplewallet/simplewallet.cpp
This is useful if you are importing your wallet into a different wallet software and want to know from what height to scan from
=> show earliest known output with wallet_info

src/simplewallet/simplewallet.cpp
It is not necessary to show account vs total balance and account labels as that data is already printed from `print_accounts()`
=> hide certain info from being repeated on balance detailed

src/wallet/wallet2.cpp
The GUI in particular does this sometimes
=> wallet2: handle paths with extensions passed to do_prepare_file_names

src/blockchain_utilities/blockchain_import.cpp
Picked from upstream to allow Masari to build on Windows as it currently does not build since sleep() was introduced in commit 934fe11
=> blockchain_import: make sleep compile on Windows

CMakeLists.txt
Not entirely sure if this was intentional or not (perhaps Boost_VERSION is returned as >106200 on some distros in some environments?).  However, I need to change this to compile on Arch Linux.
=> Typo fix in CMakeLists.txt
