- src/simplewallet/simplewallet.cpp
adjusts "fee" command to use the correct number of settings. Also changes priority settings that are output to the user from numbers to strings that are read easier
> Fix fee command

- src/simplewallet/simplewallet.cpp
only allow 0 (default), 1 (low), 2 (medium), or 3 (high)
> Only allow 3 fee priorities

- README.md
Note: masaripools.org was broken
> Update Mining Pools in README.md

- src/simplewallet/simplewallet.cpp
> simplewallet: rebased only show no-daemon message once on startup

- src/wallet/wallet2.cpp
> wallet2: update default ringdb path to match blackball.cpp

- src/simplewallet/simplewallet.cpp
otherwise the user could try to set priority level 4 and end up with a wallet exception thrown
> simplwallet: rebase simplewallet to match adf9e43

- Dockerfile
Changing daemon name from monerod to masarid
> Fix Docker ENTRYPOINT

- src/simplewallet/simplewallet.cpp
> simplewallet: handle improper log levels

- src/wallet/wallet2.cpp
> wallet2: throw wallet exception on mismatched wallet/network

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Don't try to delete a file that doesn't exist
> wallet2: only try to delete temp address file if it was created

- src/crypto/slow-hash.c
- src/cryptonote_basic/cryptonote_format_utils.cpp
add a second cryptonight variant which uses half as many loop iterations
> use cryptonight fast for proof of work

- CMakeLists.txt
- cmake/FindPCSC.cmake
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/syncobj.h
- src/cryptonote_core/blockchain.cpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
Based on Monero PRs 3550, 3574, 3536, and 3749 by moneromooo-monero, cslashm, and stoffu. These include fixes for ringdb, PCSC discovery on Windows, and auto popping blocks from blockchainDB that don't agree with the ideal fork version.
> miscellaneous updates from upstream

- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/cryptonote_boost_serialization.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
Allows uncle mining on version 2+ for testing purposes
> uncle-mining: fix serialization and verification context

- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
Grab the the tx public key and tx output from the alternative block to payout the miner of the uncle block. Will payout the uncle miner 1/2 of the nephew miner for testing purposes
> uncle-mining: Initial uncle miner reward structure

- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
make sure that the uncle miner is rewarded no more than 1/2 of the base reward, count uncle block rewards in total coins generated, and allow uncle miner to claim a 5% bonus reward if includes uncle block.
> uncle-mining: uncle mining rewards

- src/rpc/core_rpc_server.cpp
This shouldn't have made it into #90
> remove unnecessary cout

- src/rpc/core_rpc_server.cpp
Prune rct_prunable data from json encoded transaction if "prune":true is passed
> rpc: allow pruning of json encoded txs

- src/cryptonote_basic/miner.cpp
> miner: print height for block found

- src/cryptonote_basic/miner.cpp
- src/cryptonote_core/blockchain.cpp
Note: closing this branch and will resort to independent PRs for each change added (rather than one big branch) which is better for collaborative work (since core feature implementation has been merged into master)
> Miscellaneous UM related commits

- docker/Dockerfile
- docker/Readme.md
- docker/entreypoint.sh
Update Dockerfile to a working version
Add entrypoint file to add more possibilities
Add Readme file with examples on how to use
> Update docker setup

- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
Specifically 27a79e27e193396425fd3766a4885770ea07e627 822f436bb9420c22d2e4bc75e28f773ff498636c and 7fd35c67df00b3aab47e64f6ddd289935c315b68
> Update miner copyright header

- src/simplewallet/simplewallet.cpp
Otherwise you can't see the money from your other accounts without switching the current account
> simplewallet: show total balance with account balance

- src/simplewallet/simplewallet.cpp
It's not necessary to show balance and total balance together if only the current account has money on it
> simplewallet: only show total balance if other accounts are in use

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/core_tests/chaingen.cpp
- tests/core_tests/chaingen_main.cpp
- tests/core_tests/uncles.cpp
Addresses #119
Refactor uncle miner tx construction code
Swaps uncle & nephew reward positions
Disables extended ancestry case to maintain same-index tx derivation
> Resolve multi-address coinbase output detection issue

- Makefile
> Makefile: options to run individual test suits after build

- contrib/epee/include/net/abstract_tcp_server2.inl
- src/crypto/CMakeLists.txt
- src/crypto/crypto.h
- src/crypto/generic-ops.h
- src/ringct/rctTypes.h
- src/serialization/json_archive.h
> Bug fixes from upstream

- utils/build_scripts/crosscompile_scripts/QEMU.md
- utils/build_scripts/crosscompile_scripts/README.md
- utils/build_scripts/crosscompile_scripts/cross-aarch64
- utils/build_scripts/crosscompile_scripts/cross-armv7
Bash scripts for linux x86_64->armv7 & armv8a
QEMU instructions for armv7 and legacy armv6
> Cross-compile scripts for armv7 and armv8a

- src/wallet/api/wallet2_api.h
> wallet api: move isMultisig to proper class

- contrib/epee/include/net/abstract_tcp_server2.inl
Fixes building where boost > 1.70.0
refer to monero PR #5328
> fix building with boost 1.70.0

- src/rpc/core_rpc_server.cpp
Original commit from mc (Solo):
https://gitlab.com/solo-project/solo/commit/ef8dfcb66caf5cd55e0fddd53d0ef42f8d3a7e82
Noticed "Daemon: Merge print_uncle_block & print_block" ( https://trello.com/c/xXQSYiSb/3-daemon-merge-printuncleblock-printblock )
> rpc:core_rpc_server: print_block uncle support - by mc (Solo)

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Reported by cutcoin
reference: https://hackerone.com/reports/501585
> wallet2: fix mishandling rct outputs in coinbase tx
